### ISSUE TITLE
Fix light measurement are correct (and associated unit)

### ISSUE THREAD

**Issue by 3rwww1** [LaCoolCo/LaCOOLBoard#2]
The coolboard reports the light measurement in millilumens.

We should ensure that the values gathered by the sensor are correct from a physical point of view 

For instance values reported by a sensor exposed to a LED strip should be around `exepected` mlm and the sensor outputs `actual` mlm, so the mission is: 
- find the `expected` range for the LED strip case (by browsing the internet, asking around, etc)
- find the `actual` range by plugging a coolboard and looking at the output values

Same goes for direct sunlight, incandescent light, etc

**Comment by simon-lacool** [comment]
the answer is on page 3:
https://www.silabs.com/documents/public/application-notes/AN523.pdf

**Comment by 3rwww1** [comment]
Used gain value is 1.

**Comment by 3rwww1** [comment]
Implementation proposal:
- record the raw sensor values and send them through MQTT
- do the post-processing (as described in AN523) server-side. Use 250/260 as the de-facto background noise level (dark level in the AN523 PDF) for those computations.
- long-term & optimal settings for application needing the most accuracy : add a calibration step (through an UI component) aiming at calculating the background noise level (switch of the light/put the board in total darkness, measure average sensor output and use it in following computations).
